## 主配置文件 这里存放的是公共的配置信息
# 激活对应的环境的配置文件
spring:
 profiles:
  active: dev

   
myJob:
 alias:
  dir: com.iflytek.quartz.myjob.
  
## 配置项目启动的时候 scheduler 是否自动启动 默认是true 自动启动
org:
 quartz:
  scheduler:
   autoStartup: true